#!/bin/bash
set -e

echo Running ruff src
uv run ruff check --fix src
echo Running black src
uv run black src
echo Running isort src
uv run isort --profile black src
echo Running mypy src
uv run mypy src
echo Running pyright src
uv run pyright src --threads
echo Linting complete!
exit 0
