name: Linting

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.11]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4    
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Run Linting
      run: |
        ./install
        ./lint
