name: Win_Nuitka

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.10.4]
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install dependencies
      run: |
        ./install
        uv pip install -r requirements.nuitka.txt
    - name: Run Binary Build
      run: |
        uv run src/open_webdriver/tests/nuitka/test_binary_build.py
